FROM                            python:3.9
RUN                             useradd roboshop
RUN                             mkdir /app
WORkDIR                         /app
RUN                             pip3.6 install -r requirements.txt
COPY                            code/* /app/
